Make a bunch of stuff posix compliant

diff --git a/dot_shinit b/dot_shinit
--- a/dot_shinit
+++ b/dot_shinit
@@ -78,6 +78,36 @@ if command -v brew >/dev/null; then
   alias brew-upgrade='echo_run brew upgrade --ignore-pinned --display-times'
 fi
 
+venv() {
+  # Recursively search up until home directory for a virtual environment with
+  # the desired name. This allows you to activate a venv from the root of your
+  # project while you're deep in the directory structure
+  set -- "${1:-.venv}" "$PWD" "$1"
+  while [ "$2" != "$HOME" ] && [ ! -f "${2}/${1}/bin/activate" ]; do
+    set -- "$1" "$(dirname "$2")" "$3"
+  done
+
+  # If you're in a venv and you didn't specify a different one explicitly then
+  # you probably want to deactivate the current one
+  if [ -n "$VIRTUAL_ENV" ] && [ -z "$3" ]; then
+    deactivate
+    return
+  fi
+
+  if [ ! -f "${2}/${1}/bin/activate" ]; then
+    echo-err "Couldn't find a valid venv for '${1}'"
+    return 1
+  fi
+
+  # shellcheck disable=SC1090
+  . "${2}/${1}/bin/activate"
+}
+
+clone() {
+  set -- "$(FORCE_COLOR=1 echo-run command git clone "$@" 2>&1 | tee /dev/stderr | grep 'Cloning into' | cut -d \' -f2)" || return $?
+  echo_run cd "$1"
+}
+
 autoload_script() {
   # usage: autoload_script func_name /path/to/func_name
   eval "${1}() {
@@ -98,6 +128,32 @@ take() {
   mkdir -p "$1" && cd "$1"
 }
 
+alias rc="restart_sh" # Reload Config
+alias resh="restart_sh"
+restart_sh() {
+  set -- "$(which "$(ps -p $$ | tail -1 | awk '{print $4}')")"
+
+  if command -v zplug >/dev/null 2>&1; then
+    echo_run zplug reinit
+  fi
+
+  if [ -n "$(jobs)" ]; then
+    echo-warn "Current shell has backgrounded jobs. Not restarting ${1}"
+    return 1
+  fi
+
+  # Since we reset $PATH and the autoloading requires cat we need to run this
+  # first to load the echo_run script
+  echo_run echo >/dev/null 2>&1
+
+  echo_eval 'PATH=""'
+  if [ -n "$FPATH" ]; then
+    echo_eval 'FPATH=""'
+  fi
+
+  echo_run exec "$1" -li
+}
+
 new_or_switch_tmux() {
   if ! tmux has-session -t "$1" >/dev/null 2>&1; then
     echo_run tmux new-session -d -s "$1" -c "$2"
@@ -116,25 +172,28 @@ new_or_switch_tmux() {
   fi
 }
 
-exit() {
+alias exit='exit'
+_exit() {
+  # NOTE: The exit calls are prefixed with a \ so that they ignore alias
+  # expansion and prevent infinite loops
   if [ -z "$TMUX" ]; then
     # echo 'Exit if we are not in a tmux session'
-    builtin exit
+    \exit
   fi
 
   if [ "$(tmux list-windows 2>/dev/null | wc -l | tr -d ' ')" -ge 2 ]; then
     # echo 'Exit if there are other windows in the same session'
-    builtin exit
+    \exit
   fi
 
   if ! tmux list-sessions 2>/dev/null | grep --invert-match caffeinate | grep --invert-match --quiet "$(tmux display-message -p '#{session_name}')"; then
     # echo 'Exit if there are no other (useful) sessions to switch to'
-    builtin exit
+    \exit
   fi
 
   # echo 'Switch to another session'
   tmux switch-client -t "$(tmux list-sessions 2>/dev/null | grep --invert-match caffeinate | grep --invert-match "$(tmux display-message -p '#{session_name}')" | head -n 1 | cut -d ':' -f 1)"
-  builtin exit
+  \exit
 }
 
 save_venv() {
