Move run scripts to ~/bin

diff --git a/run_once_before_20-install-1password-cli.sh.tmpl b/run_once_before_20-install-1password-cli.sh.tmpl
--- a/run_once_before_20-install-1password-cli.sh.tmpl
+++ b/run_once_before_20-install-1password-cli.sh.tmpl
@@ -17,7 +17,14 @@ if [ -n "$GITHUB_WORKFLOW" ]; then
 fi
 
 {{ if eq .chezmoi.os "darwin" -}}
-brew install --cask 1password-cli
+
+if command -v brew >/dev/null 2>&1; then
+  brew install --cask 1password-cli
+else
+  echo "FAILED: brew is not installed so could not install 1password-cli"
+  exit 1
+fi
+
 {{- else }}
 
 tmpdir="$(mktemp -d)"
