Update ssh scripts

diff --git a/private_dot_local/exact_bin/executable_pubkey b/private_dot_local/exact_bin/executable_pubkey
--- a/private_dot_local/exact_bin/executable_pubkey
+++ b/private_dot_local/exact_bin/executable_pubkey
@@ -1,3 +1,11 @@
 #!/usr/bin/env zsh
 
-more ~/.ssh/id_rsa.pub | pbcopy | echo '=> Public key copied to clipboard.'
+file="${HOME}/.ssh/id_rsa.pub"
+if [ ! -f "$file" ]; then
+  file="${HOME}/.ssh/id_ed25519.pub"
+fi
+if [ ! -f "$file" ]; then
+  echo-err "Failed to find public key file in ${HOME}/.ssh" >&2
+  exit 1
+fi
+cat "$file" | pbcopy | echo-ok 'Public key copied to clipboard.'
